# (id, file, regex, note) -> current line number, re-derived every time this runs
A = [
 ("1.3/B4","Kinship.pas", r"function writeKinGEDCOM", "empty GEDCOM writer"),
 ("1.3/B4b","Kinship.pas", r"procedure header_GEDCOM", "GEDCOM header"),
 ("2.3","Kinship.pas", r"function TSimulEgoTree\.Simulate", "go-flag published before state"),
 ("2.3b","Kinship.pas", r"procedure TSimulEgoTree\.Execute", "the consumer"),
 ("2.4a","Kinship.pas", r"repeat until BigCohortWomenThreads\[ind\]\.AFinished", "hot spin"),
 ("2.4b","Kinship.pas", r"repeat until aThreadObject\.AFinished", "hot spin"),
 ("2.4c","Kinship.pas", r"repeat until gMyThreadObjects\[indThread\]\.simulate", "hot spin"),
 ("2.4d","Utilities.pas", r"^\s*until FAFinished;", "hot spin in TFileType.finished"),
 ("2.5a","Kinship.pas", r"if \( not openFileOut\(fname, 'gOUTFILEINDIVKIN'", "main file open failure"),
 ("2.5b","Kinship.pas", r"if \( not openFileOut\(fname_link", "link file failure leaves main open"),
 ("2.5c","Kinship.pas", r"if not individualKin_init \(bootstrap_ind", "caller's bare exit"),
 ("3.b","Init.pas", r"USE_ARRAY_CHILDREN := BooleanName\.Create", "constructed TRUE, defaulted FALSE"),
 ("3.d1","ReadCmdFileUnit.pas", r"//writeON_OFF \(outFile, g_GENPARAM\.DUMP,", "writer commented, reader live"),
 ("3.d2","ReadCmdFileUnit.pas", r"//writeON_OFF \(outFile, g_GENPARAM\.STABLE_POPULATION\)", "writer commented, reader live"),
 ("3.1","ReadCmdFileUnit.pas", r"writeComment \(outFile, '! KINFERT extended config file'\)", "DUMPALL writes no tables"),
 ("3.5a","ReadCmdFileUnit.pas", r"memoWriteLn\(\['Finished: '", "banner prints on the error path"),
 ("3.5b","ReadCmdFileUnit.pas", r"^\s*doIt \( filename, initAndReadFile \);", "result discarded"),
 ("3.5c","Simulxcode.pas", r"doIt \( filename_param, initAndReadFile \)", "result discarded"),
 ("3.4","lazkinoutputfields.pas", r"'yDeathFloat'", "no checkbox for fn_yDeathFloat"),
 ("6.4","Declarations.pas", r"procedure ArrayOfDoubleName\.setChanged", "needs a prior setDefault"),
 ("4.2","Kinship.pas", r"bWriteLn\(gOutFileIndivKin_link, \[indNumber, comma, pPartner", "M rows both directions"),
 ("4.6a","Kinship.pas", r"if fieldEnabled \(fn_heirs\) then bWrite \(gOutFileIndivKin, \[sep, 'heirs'\]\)", "header heirs"),
 ("4.6b","Kinship.pas", r"^\s*bWrite \(gOutFileIndivKin, \[sep, 'heirs'\]\);", "duplicate heirs header"),
 ("4.7","Kinship.pas", r"idSpouses := '0';", "sentinels disagree"),
 ("4.8","Kinship.pas", r"if \( CalcChildren \(pRelative\) <> getNumChildren \(pEgo\) \)", "redundant check"),
 ("4.11","Kinship.pas", r"stopTime \(tStart_interm, '===== post-phase of simulateKinship", "read outside the TALKATIVE guard"),
 ("5.2","Kinship.pas", r"function includeKinInNetwork", "no init, no final else"),
 ("5.6","Kinship.pas", r"// aThreadObject\.Destroy;", "would be a double free"),
    ("N6b","FertilityRuntime.pas", r"endBySeparation \(randomGenerator, monthStart, monthNow,", "separation tested twice over the spacing months"),
 ("N7","FertilityRuntime.pas", r"if \(b = 0\) then b := 0\.00001", "PPR near-certainty"),
 ("N7b","FertilityRuntime.pas", r"pDemReg\^\.adjustedValues := true", "set unconditionally"),
 ("N8","Fertility.pas", r"if \(fecundLife\.ageSterile > kMinAgeFert\) and \(fecundLife\.ageSterile < kMaxAgeFert\)", "sterility floor"),
 ("N9","StablePop.pas", r"sum := sum \+ Exp\(-r_val \* x\) \* lx\[x\] \* Fertility\[x\]", "omits proportion female"),
 ("N10","FertilityRuntime.pas", r"tnr := tnr \+ Total_NetFertility \* 0\.488", "hardcoded sex ratio"),
 ("N11","Declarations.pas", r"toObj\.next := nil", "cohort parameter lists lost"),
 ("N13","Mortality.pas", r"a := 0\.463 \+ 2\.9375 \* q0", "inverted infant correction"),
 ("N14","Mortality.pas", r"if \(e0 < lifeTable_e0_min\) or \(e0 > lifeTable_e0_max\)", "warned, not clamped"),
 ("N17","EducationalLevel.pas", r"if \(dummy < p\^\.eduEgoPartner \[eduLevelPartner, pRelative\^\.gender, eduLow\]", "wrong sex index"),
 ("N18","EducationalLevel.pas", r"if \(pRelative\^\.typeOfKin = kt_sibling\) then", "siblings not correlated"),
 ("N19a","DemographicRegime.pas", r"if g_GENPARAM\.eduKind\.value = eduStochastic then\s*$", "dump mapping shifted"),
 ("N20","EducationalLevel.pas", r"if \(dummy < 1/3\) then", "hardcoded thirds"),
 ("N22","inheritance.pas", r"procedure exploreAscendantHeirsTree_2", "nearer ascendant does not exclude"),
 ("N24","inheritance.pas", r"function commonAncestor", "computed and discarded"),
 ("N25","inheritance.pas", r"procedure lookForDecedents_Spain", "empty body"),
 ("N26","inheritance.pas", r"function checkHeirs", "reports agreement on disagreement"),
 ("N28","Nuptiality.pas", r"procedure setAgeUnion \(pRelative", "phantom union on out-of-range index"),
 ("N29","Nuptiality.pas", r"scaleFactor := \(mean - ageMin\) / 11\.37", "can be zero or negative"),
 ("N30","Nuptiality.pas", r"std := 107\.0 \* ln \(mean\) - 292\.0", "sqrt of a negative"),
 ("N31","Nuptiality.pas", r"function ageWomenEndUnion", "negative age labelled widow"),
 ("N32","Nuptiality.pas", r"^try // 1", "handler falls through"),
 ("N34","Parenthood.pas", r"Inc \(distNbChildren \[allStates50, nbChildren\]\)", "unatomic shared counter"),
 ("N35","Kinship.pas", r"if \(cohortMan < gFirstCohortGrooms\) or \(cohortMan > gLastCohortGrooms\) then exit", "exit where continue is needed"),
 ("N36","Kinship.pas", r"BigCohortWomenThreads\[ind\]\.Destroy", "no WaitFor, no inherited"),
 ("N37","Kinship.pas", r"gBig_ArrayWomen := TPersonMemoryManager\.Create\(\)", "800 MB no-arg allocation"),
 ("N38","Kinship.pas", r"until \(nActiveThreads <= 0\)", "not a count of running threads"),
 ("N39","mothersInfoList.pas", r"^unit ", "dead file, still tracked"),
 ("N41","Kinship.pas", r"SetLength \(gMen_Women, gLastCohortGrooms", "stale arrays across replicates"),
 ("N42","DemographicRegime.pas", r"myRandomGenerator\.initRandomized\(\)", "seed race in the worker"),
 ("N43","DemographicRegime.pas", r"allThreadsDead := false;", "half the exit test is dead"),
 ("N44","DemographicRegime.pas", r"Destructor TDemRegInitThread\.Destroy", "no inherited Destroy"),
 ("N45","StringOfLib.pas", r"while \(Result\[length\(Result\)\] = '0'\) do", "trailing-zero strip"),
 ("N46","Nuptiality.pas", r"writeArrayOfDouble\(f, tab, d\.monthly_risk_separation, true\)", "4 args to a 3-arg proc"),
 ("N49","FertilityRuntime.pas", r"procedure addChild \(age: FecundAges", "out where var is needed"),
 ("N4c","FertilityRuntime.pas", r"if g_GENPARAM\.fixedParameters \[reshuffledFecundability\]", "redraw discards the taper"),
 ("B1","ReadCmdFileUnit.pas", r"for bootstrap_index := 1 to g_GENPARAM\.RUNTIME\[gBootstrap_nRuns\]", "the replicate loop"),
 ("D4","Utilities.pas", r"function openFileKeys", "keys needed for sweeps too"),
 ("Erlang","Fertility.pas", r"temp := power \(lambda, k\) \* power \(i, k - 1\)", "power(0,k-1), never normalised"),
 ("Arith1","FertilityRuntime.pas", r"sum := 1\.0 / sum;", "division by zero on an empty cohort"),
 ("Arith2","FertilityRuntime.pas", r"history\[prior, -1\] := pDemReg\^\.dp\[freqSeparationFirstIteration\]", "extra Inc leaves history[.,1] unset"),
 ("Arith3","FertilityRuntime.pas", r"pDemReg\^\.separationInfo\.freqSeparation_result := pData\^\.propFinalSeparation", "read uninitialised"),
 ("Arith4","DemographicRegime.pas", r"pDemReg\^\.eduEgo \[EduLevels\(dPos", "unchecked table index"),
 ("Dead1","Utilities.pas", r"procedure writeOneArrayOfDouble", "no callers"),
 ("Dead2","testThread.pas", r"^unit ", "unit name does not match the file"),
]
import re,io,sys
out=[]
for iid,f,rx,note in A:
    try: lines=io.open(f,encoding='utf-8',errors='replace').read().split('\n')
    except Exception as e: out.append((iid,f,"FILE MISSING",note)); continue
    hits=[i+1 for i,l in enumerate(lines) if re.search(rx,l)]
    if not hits: out.append((iid,f,"ANCHOR NOT FOUND",note))
    else: out.append((iid,f,",".join(str(h) for h in hits[:6]),note))
for iid,f,ln,note in out:
    print("%-10s %-24s %-22s %s"%(iid,f,ln,note))
